version: '2.4'
services:

  mysql:
    extends:
      file:    extends/mysql.yml
      service: mysql
    container_name: fleetdm-mysql
    hostname:       fleetdm-mysql
    volumes:
    - type:   volume
      source: data_fleetdm
      target: /var/lib/mysql
    command: ['--server-id=2', '--report-host=fleetdm-mysql']
    ports:   ['3306:3306']
    networks: ['network_fleetdm']

  redis:
    extends:
      file:    extends/redis.yml
      service: redis
    container_name: fleetdm-redis
    hostname:       fleetdm-redis
    networks: ['network_fleetdm']

  fleetdm:
    extends:
      file:    extends/fleetdm.yml
      service: fleetdm
    container_name: fleetdm
    hostname:       fleetdm
    environment:
      FLEET_REDIS_ADDRESS:  fleetdm-redis:6379
    depends_on: ['mysql', 'redis']
    ports:      ['80:80']
    networks: ['network_fleetdm']
    
    
volumes:
  data_fleetdm:
    name:   data_fleetdm
    driver: local


networks:
  network_fleetdm:
    name:   network_fleetdm
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_fleetdm_nat
    ipam:
     driver: default

    